</div>

    <footer class="footer">

      <div class="container">
        <p class="pull-right">
            <a href="">NoP</a> Powered by <a href="https://github.com/tomyhero/Ze">Ze</a>
        </p>
      </div>
    </footer>

        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
        <script src="/static/common/js/jquery.cookie.js"></script>
        <script src="/static/common/js/jquery.ze.js"></script>
[% footer_content %]
</body>
</html>
